#! /bin/sh

image="$1"

old_id=$(docker image inspect ${image} | jq -r '.[0].Id')
docker pull ${image}
new_id=$(docker image inspect ${image} | jq -r '.[0].Id')

if ! test "${old_id}" = "${new_id}"
  then
		echo "CHANGE"
		exit 0
  fi

echo "OK"
exit 0
