#! /bin/sh

image="$1"
if ! test "$(skopeo inspect docker://${image} | jq -r .Digest)" = "$(docker image inspect ${image} | jq -r '.[0].Id')"
  then
    if ! docker pull ${image}
    	then
			echo "CHANGE"
			exit 0
    	fi
    exit 1
  fi

echo "OK"
exit 0
