#! /bin/sh

if test -z "$*"
  then
    echo "Usage: $0 <hosts/groups to install>"
    exit 1
  fi

. ./ansible_vault_password.inc

ansible-playbook -e "${EXTRA_VARS}" -b -i ./${INVENTORY:-inventory.yaml} -l "$*" ./${PLAYBOOK:-install.yaml} \
  --vault-password-file "${vault_pass_file}" \
  --become-password-file ~/.ssh/pass

# replace `--become-password-file ~/.ssh/pass` with `-K` if you prefer to be prompted for the `sudo` password
# add `-k` if you are using passwords instead of ssh-keys for the initial login
