#! /bin/sh

if test -z "$*"
  then
    echo "Usage: $0 <hosts/groups to install>"
    exit 1
  fi

pass="${HOME}/.handshake_vault_password"
if ! test -f ${pass}
	then
		dd if=/dev/random bs=1 count=24 2>/dev/null | base64 > ${pass}
	fi

ansible-playbook -e "${EXTRA_VARS}" -b -i ./${INVENTORY:-inventory.yaml} -l "$*" ./${PLAYBOOK:-install.yaml} \
  --vault-password-file "${pass}" \
  --become-password-file ~/.ssh/pass

# replace `--become-password-file ~/.ssh/pass` with `-K` if you prefer to be prompted for the `sudo` password
# add `-k` if you are using passwords instead of ssh-keys for the initial login
