#! /bin/sh

if test -z "$*"
	then
		echo "Usage: $0 <key and certificate file(s)>"
		exit 1
	fi

if ! grep -q -- "-BEGIN CERTIFICATE-" $*
	then
		echo "ERROR: server.pem needs to include a CERTIFICATE"
		exit 1
	fi

if ! grep -q -- "-BEGIN PRIVATE KEY-" $*
	then
		echo "ERROR: server.pem needs to include a PRIVATE KEY"
		exit 1
	fi

awk 'BEGIN {
	print "---"
	print "handshake_mailserver_server_pem:"
	}
	{
	printf "  - \"%s\"\n",$0
	}' $* > group_vars/handshake_mailserver/server_pem.yaml

pass="${HOME}/.handshake_vault_password"
if ! test -f ${pass}
	then
		dd if=/dev/random bs=1 count=24 2>/dev/null | base64 > ${pass}
	fi

ansible-vault encrypt --vault-password-file "${pass}" group_vars/handshake_mailserver/server_pem.yaml
