#! /bin/sh

if test -z "$*"
	then
		echo "Usage: $0 <key and certificate file(s)>"
		exit 1
	fi

if ! grep -q -- "-BEGIN CERTIFICATE-" $*
	then
		echo "ERROR: server.pem needs to include a CERTIFICATE"
		exit 1
	fi

if ! grep -q -- "-BEGIN PRIVATE KEY-" $*
	then
		echo "ERROR: server.pem needs to include a PRIVATE KEY"
		exit 1
	fi

awk 'BEGIN {
	print "---"
	print "handshake_mailserver_server_pem:"
	}
	{
	printf "  - \"%s\"\n",$0
	}' $* > group_vars/handshake_mailserver/server_pem.yaml

. ./ansible_vault_password.inc

ansible-vault encrypt --vault-password-file "${vault_pass_file}" group_vars/handshake_mailserver/server_pem.yaml
