#! /bin/sh

dst="group_vars/powerdns_primary/mysql_password.yaml"

{
echo "---"
echo "powerdns_primary_mysql_password: \"$(dd if=/dev/random bs=1 count=24 2>/dev/null | base64)\""
} > ${dst}

. ./ansible_vault_password.inc

ansible-vault encrypt --vault-password-file "${vault_pass_file}" ${dst}
